#!/usr/bin/env bash
# Shared helpers for the Phase 1 resolver.  This file deliberately never
# evaluates package metadata: Debian SOURCE is parsed as data only.
set -euo pipefail


die() {
  local code=$1
  shift
  printf '%s\n' "$*" >&2
  exit "$code"
}

need() {
  command -v "$1" >/dev/null 2>&1 || die 2 "missing command: $1"
}

is_sha256() { [[ $1 =~ ^[0-9a-f]{64}$ ]]; }
is_commit() { [[ $1 =~ ^[0-9a-f]{40}$ ]]; }

# Keep the full PVE release, including KREL_EXTRA.  Comparing only the
# upstream version would incorrectly treat 7.0.14-16-pve and a backport as
# interchangeable build targets.
is_pve_kver() {
  [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+-[0-9]+[A-Za-z0-9.+~:-]*-pve$ ]]
}

json_error() {
  jq -cn --arg status "$1" --arg message "$2" \
    '{schema_version: 1, resolution_status: $status, error: $message, target:null, headers:null, source:null, integrity:null, build:null}'
}

sha256_file() {
  sha256sum -- "$1" | awk '{print $1}'
}

# This is intentionally a parser, not a shell source.  It accepts the exact
# two-line format generated by Makefile's debian.prepared target.
# See Makefile:103-104 in this repository.
pve_commit_from_source() {
  local source_file=$1 line commit=''
  while IFS= read -r line || [[ -n $line ]]; do
    case $line in
      'git checkout '*)
        commit=${line#git checkout }
        ;;
    esac
  done < "$source_file"
  is_commit "$commit" || return 1
  printf '%s\n' "$commit"
}

validate_target_json() {
  local file=$1
  jq -e '
    .schema_version == 1 and
    (.resolution_status | IN("fixture-ready", "resolved", "waiting-headers", "waiting-source", "unsupported")) and
    (if .resolution_status == "unsupported" then (.error|type=="string") else true end) and
    (if .resolution_status == "unsupported" then true else (.target.kver | type == "string") end) and
    (.target.architecture | type == "string") and
    (.target.kernel_package.name | type == "string") and
    (.target.kernel_package.version | type == "string") and
    (.build | has("toolchain") and has("vermagic") and has("artifact_sha256")) and
    (if .resolution_status == "fixture-ready" then
       (.headers.status == "ready" and (.source.pve_commit | test("^[0-9a-f]{40}$")) and
        (.source.ubuntu_kernel_commit | test("^[0-9a-f]{40}$") ) and
        (.source.patches | type == "array") and
        (.source.patches | all(.sha256 | test("^[0-9a-f]{64}$"))) and
        (.integrity.headers_config_sha256 | test("^[0-9a-f]{64}$")) and
        (.integrity.module_symvers_sha256 | test("^[0-9a-f]{64}$")))
     else true end)
  ' "$file" >/dev/null
}
